CREATE TABLE worker (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        firstname VARCHAR(50) NOT NULL,
                        lastname VARCHAR(50) NOT NULL,
                        manager VARCHAR(50),
                        status VARCHAR(50),
                        deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE department (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL
);

CREATE TABLE worker_department (
                                   worker_id BIGINT NOT NULL,
                                   department_id BIGINT NOT NULL,
                                   PRIMARY KEY (worker_id, department_id),
                                   FOREIGN KEY (worker_id) REFERENCES worker(id),
                                   FOREIGN KEY (department_id) REFERENCES department(id),
                                   deleted BOOLEAN DEFAULT FALSE
);
